train:
  _target_: dataloaders.extended_action_dataset.ExtendedActionDataset
  config:
    _target_: dataloaders.utils.DataLoaderConfig
    dataset_root: ${env_vars.finetune_task_data_root}
    trajectory_roots:
      _target_: dataloaders.utils.load_trajectory_roots
      trajectory_root_path: ${dataset.train.config.dataset_root}/r3d_files.txt
      original_root: ${env_vars.finetune_task_data_original_root}
      new_root: ${dataset.train.config.dataset_root}
    include_tasks: 
      - ${include_task}
    exclude_homes: []
    exclude_envs: []
    sequence_length: ${obs_window_size}
    control_timeskip: ${control_timeskip}
    # n_passes: 9
    safe_action_threshold: 0.1
    relative_gripper: False
    use_depth: ${use_depth}
  max_videoreaders_in_memory: 64
  shuffle_mode: RANDOM_ORDER
  device: cpu
  num_extra_actions: ${num_extra_actions}


test:
  _target_: dataloaders.extended_action_dataset.ExtendedActionDataset
  config:
    _target_: dataloaders.utils.DataLoaderConfig
    dataset_root: ${env_vars.finetune_task_data_root}
    trajectory_roots:
      _target_: dataloaders.utils.load_trajectory_roots
      trajectory_root_path: ${dataset.test.config.dataset_root}/r3d_files.txt
      original_root: ${env_vars.finetune_task_data_original_root}
      new_root: ${dataset.test.config.dataset_root}
    include_tasks: 
      - ${include_task}
    exclude_homes: []
    exclude_envs: []
    sequence_length: ${obs_window_size}
    control_timeskip: ${control_timeskip}
    # n_passes: 9
    safe_action_threshold: 0.1
    relative_gripper: False
    use_depth: ${use_depth}
  max_videoreaders_in_memory: 64
  shuffle_mode: RANDOM_ORDER
  device: cpu
  num_extra_actions: ${num_extra_actions}
